"""Update IngestedDocument model schema

Revision ID: 43c40d9dfe40
Revises: 2df007100f62
Create Date: 2025-04-18 21:40:32.546503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.ext.asyncio
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43c40d9dfe40'
down_revision: Union[str, None] = '2df007100f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_documents',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('chunk_count', sa.Integer(), nullable=True),
        sa.Column('memory_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('document_hash', sa.String(), nullable=True),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('content_type', sa.String(), nullable=True),
        sa.Column('size_bytes', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('document_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingested_documents_document_hash'), 'ingested_documents', ['document_hash'], unique=False)
    op.create_index(op.f('ix_ingested_documents_filename'), 'ingested_documents', ['filename'], unique=False)
    op.create_index(op.f('ix_ingested_documents_id'), 'ingested_documents', ['id'], unique=False)
    op.create_index(op.f('ix_ingested_documents_user_id'), 'ingested_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingested_documents_user_id'), table_name='ingested_documents')
    op.drop_index(op.f('ix_ingested_documents_id'), table_name='ingested_documents')
    op.drop_index(op.f('ix_ingested_documents_filename'), table_name='ingested_documents')
    op.drop_index(op.f('ix_ingested_documents_document_hash'), table_name='ingested_documents')
    op.drop_table('ingested_documents')
    # ### end Alembic commands ### 